name = "sw-course-devops"
main = "src/index.js"
account_id = "91e974c20bba4ec0edcc390daf40a976"
compatibility_date = "2025-06-08"

[[kv_namespaces]]
binding = "TODOS"
id = "9891d05674bb46f28ce83ba29832682e"

[env.dev]
name = "sw-course-devops"

[[env.dev.kv_namespaces]]
binding = "TODOS_DEV"
id = "680fe7ffcef640758ea1bfb1ca26c9fa"